framework:
    messenger:
        failure_transport: failed

        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                # ❌ SUPPRIME use_notify et check_delayed_interval
                # Ces options sont pour Doctrine, pas AMQP
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 0

                # ✅ Options AMQP valides
                options:
                    exchange:
                        name: messages
                        type: direct
                    queues:
                        messages: ~

            failed:
                dsn: 'doctrine://default?queue_name=failed'

        routing:
            'App\Message\*': async
            'Symfony\Component\Mailer\Messenger\SendEmailMessage': async
            'Symfony\Component\Notifier\Message\ChatMessage': async
            'Symfony\Component\Notifier\Message\SmsMessage': async
